source 'http://rubygems.org'

gem 'cucumber'
gem 'selenium-cucumber'
gem 'selenium-webdriver'
gem 'rspec'
gem 'rake'
gem 'browserstack-local'
gem 'parallel_tests'
gem 'appium_lib'
gem 'touch_action'
gem 'allure-cucumber'
gem 'allure-ruby-commons'
